name: Impact Report

on:
  workflow_dispatch:
    inputs:
      package_manager:
        description: 'Package Manager'
        required: true
        type: choice
        options:
          - npm
        default: 'npm'
      package_name:
        description: 'Package Name'
        required: true
        type: string
      verbose:
        description: 'Verbose'
        required: false
        type: boolean
        default: false

jobs:
  impact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v3

      - name: Build
        run: |
          npm install
          npm run build
          ls dist

      - name: Create test directory
        run: |
          mkdir impact-report
          cd impact-report
          npm init -y
          npm install ${{ github.event.inputs.package_name }} --verbose
          ls node_modules/${{ github.event.inputs.package_name }}

      - name: Run depsweep
        working-directory: impact-report
        run: |
          node --trace-warnings ../dist/index.js --measure-impact --ignore ../package.json ${{ github.event.inputs.verbose && '--verbose' || '' }} 2>../error.log > ../output.txt || {
            echo "Error running depsweep. Error log:"
            cat ../error.log
            exit 1
          }
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat ../output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
